apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ricky_capstoneproject_cohort1-notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URL
              value: "mongodb://root:root@mongodb:27017/notification_db?authSource=admin"

            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP