apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: ricky_capstoneproject_cohort1-rating-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URL
              value: "mongodb://root:root@mongodb:27017/rating_db?authSource=admin"

            - name: CAKE_CATALOG_URL
              value: "http://cake-catalog:3000"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP